name: DRBN_UpSampling_Corner_Huawei_tune3
use_tb_logger: true
model_type: DRBNModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
#### datasets

datasets:
  train:
    name: Huawei
    type: PairedImageDataset
    dataroot_gt: /LLIE/Huawei/train/high
    dataroot_lq: /LLIE/Huawei/train/low
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    use_flip: true
    use_rot: true
    gt_size: 256

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: Huawei
    type: PairedImageDataset
    dataroot_gt: /LLIE/Huawei/test/high
    dataroot_lq: /LLIE/Huawei/test/low
    io_backend:
      type: disk


#### network structures
network_g:
  type: DRBN_UpSampling_Corner
  n_color: 3

#### path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

#### training settings: learning rate scheme, loss

train:
  ema_decay: 0.0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000, 250000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up
  dual: False

  # losses
  pixel_opt:
    type: SSIMLoss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~